### ISSUE TITLE
Rails 6 issue?

### ISSUE THREAD

**Issue by ghost** [OpenGems/redis_web_manager#22]
I alas don't have time to dig deeply into this right now, but this gem doesn't appear to be playing well with some combination of Rails 6 and RSpec. It's working fine for me in development, but when I try to run specs:

```
An error occurred while loading ./spec/views/pages/dashboard.html.haml_spec.rb.
Failure/Error: require File.expand_path('../config/environment', __dir__)

FrozenError:
  can't modify frozen #<Class:#<Array:0x00007f81fd310c78>>
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/change_observer.rb:20:in `unshift'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/change_observer.rb:20:in `unshift'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/railties-6.0.2.1/lib/rails/engine.rb:575:in `block in <class:Engine>'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/railties-6.0.2.1/lib/rails/initializable.rb:32:in `instance_exec'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/railties-6.0.2.1/lib/rails/initializable.rb:32:in `run'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/railties-6.0.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/railties-6.0.2.1/lib/rails/initializable.rb:50:in `each'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/railties-6.0.2.1/lib/rails/initializable.rb:50:in `tsort_each_child'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/railties-6.0.2.1/lib/rails/initializable.rb:50:in `each'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/railties-6.0.2.1/lib/rails/initializable.rb:50:in `tsort_each_child'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/railties-6.0.2.1/lib/rails/initializable.rb:50:in `each'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/railties-6.0.2.1/lib/rails/initializable.rb:50:in `tsort_each_child'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/railties-6.0.2.1/lib/rails/initializable.rb:50:in `each'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/railties-6.0.2.1/lib/rails/initializable.rb:50:in `tsort_each_child'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/railties-6.0.2.1/lib/rails/initializable.rb:50:in `each'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/railties-6.0.2.1/lib/rails/initializable.rb:50:in `tsort_each_child'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/railties-6.0.2.1/lib/rails/initializable.rb:50:in `each'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/railties-6.0.2.1/lib/rails/initializable.rb:50:in `tsort_each_child'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/railties-6.0.2.1/lib/rails/initializable.rb:60:in `run_initializers'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/railties-6.0.2.1/lib/rails/application.rb:363:in `initialize!'
# ./config/environment.rb:7:in `<main>'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `require'
# ./spec/rails_helper.rb:7:in `<main>'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `require'
# ./spec/views/pages/dashboard.html.haml_spec.rb:3:in `<main>'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
# /Users/mike/.rvm/gems/ruby-2.6.4@greenandred/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
```

Looking at that stack trace I suspect an incompatibility with the new Zeitwork class loader, but that's just a guess at this point.

**Comment by ghost** [comment]
Never mind. That was the obscure way for Rails to say "you're referencing a gem in routes that you're not loading in the test environment." Sorry for the noise.
